checkoutLocation: "./esp32-toolkit-lib"
workspaceLocation: "."
tasks:
  - name: Workspace Setup
    env:  
      PROJECT_ARTIFACT_URL: 'https://github.com/etienne1911/esp32-toolkit-lib/releases/download'
      PROJECT_ARTIFACT_REL: 'r2'
      PROJECT_ARTIFACT_NAME: 'pio-workspace-artifact' #esp32-pio-workspace
      SCRIPTS_DIR: src/modules/pwa-tools/scripts/
    init: |
      wget $PROJECT_ARTIFACT_URL/$PROJECT_ARTIFACT_REL/$PROJECT_ARTIFACT_NAME.zip
      echo 'workspace artifact retrieved'
      unzip ${PROJECT_ARTIFACT_NAME}.zip
      echo 'done extracting workspace artifact'
      pwd && ls -la
      # remove artifact
      rm ${PROJECT_ARTIFACT_NAME}.zip
      # substitute lib in workspace artifact to use current repo
      rm -rf lib/esp32-toolkit-lib/ && mv esp32-toolkit-lib/ lib/
      # make symlinks
      ln -s lib/esp32-toolkit-lib/.config/platformio.ini platform.ini
      ln -s lib/esp32-toolkit-lib/.config/.gitmodules .gitmodules
      ln -s lib/esp32-toolkit-lib/.config/scripts/replace_fs.py replace_fs.py
      ln -s ../lib/esp32-toolkit-lib/examples/firmware-main.cpp src/main.cpp
    command: |
      python -m pip install --upgrade pip
      pip install --upgrade platformio
      cd /workspace
      # rm src/main.cpp && ln -s lib/esp32-toolkit-lib/examples/firmware-base.cpp src/main.cpp && pio run 
