name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      LIB_NAME: exp32-toolkit-lib
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # - uses: actions/checkout@v2
    - name: dbg
      run: |
        pwd && ls -la
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Setup PlatformIO project
      run: |
        pio init --board esp32doit-devkit-v1
        ls -la 
    - uses: actions/checkout@v2
      with:
        path: lib/exp32-toolkit-lib
    - name: Configure workspace
      run: |
        cp lib/$LIB_NAME/.config/platformio.ini ./
        cp lib/$LIB_NAME/.config/main.cpp ./
        cp lib/$LIB_NAME/.config/.gitmodules ./
        cp lib/$LIB_NAME/.config/scripts/replace_fs.py .
        wget -O mklittlefs.tar.gz $MKLITTLEFS_BIN_URL && tar -xf mklittlefs.tar.gz && mv mklittlefs/mklittlefs ./
        wget $DIGIPOT_LIB_URL && unzip DigiPotX9Cxxx.zip && mv DigiPotX9Cxxx/ lib/
        pwd && ls -laR
